export { default as Home } from './Home/Home'
export { default as Phones } from './Phones/Phones'
export { default as Computers } from './Computers/Computers'
export { default as Watches } from './Watches/Watches'
export { default as Cameras } from './Cameras/Cameras'
export { default as Gaming } from './Gaming/Gaming'
export { default as Tablets } from './Tablets/Tablets'
export { default as Tvs } from './Tvs/Tvs'